[build-system]
requires = [ "setuptools>=80.9.0", "wheel",]
build-backend = "setuptools.build_meta"

[project]
name = "universal-skills"
version = "0.1.0"
description = "Integrate RAG into AI Agents via MCP Server. Supports multiple Vector database technologies."
readme = "README.md"
classifiers = [ "Development Status :: 5 - Production/Stable", "License :: Public Domain", "Environment :: Console", "Operating System :: POSIX :: Linux", "Programming Language :: Python :: 3",]
requires-python = ">=3.10"
dependencies = [ ]
[[project.authors]]
name = "Audel Rouhi"
email = "knucklessg1@gmail.com"

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
universal_skills = [ "skills/**" ]

[tool.setuptools.packages.find]
where = [ ".",]
